# Development Docker Compose with hot reload
version: '3.8'

services:
  signaling-server:
    build:
      context: .
      args:
        NODE_ENV: development
        INSTALL_DEV: 'true'
    container_name: screen-mirror-signaling-dev
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      # Mount source code for hot reload
      - ./server.js:/app/server.js
      - ./shared:/app/shared
      - ./package.json:/app/package.json
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
